### ISSUE TITLE
Redo customization for Scratchr2 userstyle?

### ISSUE THREAD

**Issue by mxmou** [mxmou/customize-scratch#11]
Currently how customization in the Scratchr2 userstyle works is that every color can be configured separately. This has some problems:

- Quite a lot of code is used to apply this customization to 3.0-styled pages.
- It's very easy to create a combination where some non-customizable colors (e.g. gray text) have poor contrast with the chosen colors, making text hard to read.
- The only uses for customization I know is to make text white on black (like dark mode), which means that the ability to change text and background colors separately isn't really needed.

For version 2.0 of this userstyle, I'm planning to:
- Remove most of customization, except primary (used by navigation bar and forum post headers) and active (used by links on hover) colors.
- Separate primary and link color, so it would be possible to have a white navigation bar even when not in dark mode, without making links hard to see.
- Add the ability to toggle between white and black text on the navigation bar, making it possible to choose a light primary color.
- Add dark mode.

I would like to know what others think about this.

**Edit:** I'm going to implement this. Thanks to everyone who commented - feel free to give more feedback if you want.

**Comment by BoomerScratch** [comment]
Sounds good! 👍

**Comment by Wicycool** [comment]
Yeah, currently whenever I try to change the background to something dark, it doesn't look good with the white borders that boxes have, so a built in dark mode would be nice!

**Comment by mxmou** [comment]
@BoomerScratch @Ezlambry Thanks for feedback. Jeffalo also said it's OK, so I'm going to implement this.

**Comment by mxmou** [comment]
Here is what it looks like at the moment:
![Scratchr2 dark mode](https://user-images.githubusercontent.com/51849865/84576764-829a6b80-adb7-11ea-8f51-3faaaee2106e.png)
![Scratchr2 dark mode with customized colors](https://user-images.githubusercontent.com/51849865/84576911-6e0aa300-adb8-11ea-9f3e-00801cab75ee.png)
I don't like light gray scrollbars on dark background, so I made the scrollbar dark to.

**Comment by Explosion-Scratch** [comment]
Wow, as always your work amazes me. Total support for this update. Hopefully sometime this usercript can be implemented in scratch.

**Comment by mxmou** [comment]
2.0 is released, the new features are currently experimental.
