### ISSUE TITLE
Consider removing discuss link?

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#12]
In the suggestion for this extension someone mentioned that the ST wern't super fond of te discuss link in the header, perhaps remove that? It would make this more likely to be implemented.

**Comment by mxmou** [comment]
The discuss link is not a part of the Scratchr2 userstyle - it's a completely separate userscript. Maybe you should mention that in the OP on the suggestion.

**Comment by Explosion-Scratch** [comment]
Whoops!
