### ISSUE TITLE
The page scratch.mit.edu/info/quotes does not have the scratch 3.0 style.

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#13]
https://scratch.mit.edu/info/quotes does not have the new header and 3.0 style. Otherwise amazing job! Also I doubt this page gets many views, but maybe change it just for the sake of consistency?

**Comment by WorldLanguages** [comment]
lol nice catch

**Comment by mxmou** [comment]
I will update it, although I never knew it exists lol

**Comment by Explosion-Scratch** [comment]
@mxmou okay! Thanks!

**Comment by mxmou** [comment]
Reopening as it isn't fixed yet.
