### ISSUE TITLE
https://scratch.mit.edu/info/ext_download/ does not have the scratchr2 theme.

### ISSUE THREAD

**Issue by tb148** [mxmou/customize-scratch#15]

**Comment by Explosion-Scratch** [comment]
Wait, did youfix it? :P

**Comment by mxmou** [comment]
> Wait, did youfix it? :P

Yes, I did because it [was very easy](https://github.com/mxmou/customize-scratch/commit/862ae4d7cc955b72e9759744feba5dfa322e9b06).

**Comment by Explosion-Scratch** [comment]
Okay! Cool!
