### ISSUE TITLE
Userscripts and userstyles collection

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#16]
Okay, I think it's probably about time to start gathering userstyles and userscripts in an organized manner. This issue can be the collection of those.

*How to submit a userstyle or userscript*
Fill in this form:

Userscript or userstyle name:
Description:
Creator:
Link to where you found it (e.g. github, scratch AT forums etc.):
Link to raw code:
Raw code (in case the raw code link breaks):

Then do these steps:
- Archive the link where you found it with archive.org
- Also archive the link to the raw code.
- After archiving archuve this issue as well (we can do this periodically I guess)
- These steps are nessecary to make sure that we have a backup copy in case the ST deletes the discuss page or the creator unshares it from github.

Okay, that's it! Thanks to @Mxmou (MaxiMouse) and @WorldLanguages (World_Languages) and @tb148 for helping with this project! 
(Maximouse if you feel like this is not a good way to go about archiving userstyles and userscripts please close the issue :)  )

**Comment by mxmou** [comment]
> (Maximouse if you feel like this is not a good way to go about archiving userstyles and userscripts please close the issue :) )

It's OK for now, but this project should get its own repo at some point.

**Comment by Explosion-Scratch** [comment]
Okay, do you want to make one and transfer the two issues?

**Comment by mxmou** [comment]
> Okay, do you want to make one and transfer the two issues?

I thought @WorldLanguages would make it?

**Comment by Explosion-Scratch** [comment]
Okay, we'll wait for them. You seem to be more active on Github though so maybe you should?

**Comment by Explosion-Scratch** [comment]
Also depending on if this gets famous or not the most recognized person might be the repo owner so if anyone deserves that fame between WorldLanguages, you and me, it's obviously you.

**Comment by mxmou** [comment]
> Also depending on if this gets famous or not the most recognized person might be the repo owner so if anyone deserves that fame between WorldLanguages, you and me, it's obviously you.

Well, I think the person which deserves fame is the one who does the most work, and at the moment it looks like this is going to be WorldLanguages.

**Comment by Explosion-Scratch** [comment]
@mxmou. Totally true. I was just thinking that you're the only one out of the three of us without thousands of followers, why don't we see what @WorldLanguages thinks.

**Comment by mxmou** [comment]
@Explosion-Scratch What if the repo was in an organization?

**Comment by Explosion-Scratch** [comment]
That'd be good I guess :)

**Comment by Explosion-Scratch** [comment]
I'm closing this issue until a working copy of the addon is ready to install userscripts to.
