### ISSUE TITLE
Rename the userstyle?

### ISSUE THREAD

**Issue by mxmou** [mxmou/customize-scratch#17]
_Scratchr2_ isn't really the name of the userstyle (it's the Scratch 2.0 website, which the userstyle changes). I just call it "my userstyle", so would it make sense to rename it to _Maximouse's userstyle_? It's strange but that would at least make sense. Let me know if you know any better name.

**Comment by Explosion-Scratch** [comment]
Hmm, what about "Scratch 3.0" or "2.0 --> 3.0" or something

**Comment by mxmou** [comment]
> Hmm, what about "Scratch 3.0" or "2.0 --> 3.0" or something

Maybe "Scratch 2.0 → 3.0".

**Comment by mxmou** [comment]
I'm going to use "Scratch 2.0 → 3.0" (thank you for the suggestion, @Explosion-Scratch). This will be a part of the refactoring update I mentioned in another issue.

**Comment by Explosion-Scratch** [comment]
This should probably be closed now

**Comment by mxmou** [comment]
> This should probably be closed now

I will close it when it actually gets renamed.

**Comment by mxmou** [comment]
Probably won't be worked on. Use the Scratch Addons version of the userstyle instead.
