### ISSUE TITLE
Mystuff page header is messed up

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#19]
So on Firefox (I haven't tested any other browsers), the mystuff page header where it shows the thing where you can switch between studios, trash etc. it is WAY far to the right of enerything else. I'll post a screenshot soon.

**Comment by mxmou** [comment]
OK, I'm going to try it myself because I haven't tested this on Firefox much yet.

**Comment by mxmou** [comment]
![ff_scratchr2_mystuff_bug](https://user-images.githubusercontent.com/51849865/88926002-a5081b80-d275-11ea-99fa-9fe90a8b35e1.png)
Yes, it's really a problem. Let's see what I can do to fix it.

**Comment by Explosion-Scratch** [comment]
Wow! Thanks!
