### ISSUE TITLE
Make's studio project not load

### ISSUE THREAD

**Issue by devxan** [mxmou/customize-scratch#20]
Your [Scratch 2.0 parts to 3.0 userstyle](https://mxmou.github.io/customize-scratch/scratchr2.user.css) makes projects in studios not load. Could you fix this? (Cause I love the user style but don't want to delete it. @mxmou

**Comment by mxmou** [comment]
What exactly do you mean by "not load"? If you mean the next page not loading when you scroll to the bottom, that's a Scratch bug - try zooming out.

**Comment by devxan** [comment]
@mxmou when I scroll down on [this](https://scratch.mit.edu/studios/5801569/) studio, I can get no more than sixty results as I scroll down. When I disable the userstyle, I get 120 projects/results. Do you think you could create a load more button in the userstyle or something for the projects tab of studios? Edit: BTW, zooming out doesn't do anything to help.

**Comment by mxmou** [comment]
> @mxmou when I scroll down on [this](https://scratch.mit.edu/studios/5801569/) studio, I can get no more than sixty results as I scroll down. When I disable the userstyle, I get 120 projects/results. Do you think you could create a load more button in the userstyle or something for the projects tab of studios? Edit: BTW, zooming out doesn't do anything to help.

I have to zoom out to see the next page, even if the userstyle is disabled. But it does change the height of some elements, so this might be the problem in your case.

Anyway, the way Scratch detects when you scroll to the bottom is weird and I don't think there is anything I can do about it. Userstyles only control the appearance of pages and thus cannot add functional buttons.

**Comment by devxan** [comment]
Could you possibly create a userscript that adds a button to load more projects in studio's (and disables the auto-load for people who want that)? @mxmou

**Comment by mxmou** [comment]
> Could you possibly create a userscript that adds a button to load more projects in studio's (and disables the auto-load for people who want that)? @mxmou

Yes, I might do that. Closing this now.

**Comment by devxan** [comment]
> Yes, I might do that. Closing this now.

Thank you, @mxmou!
