### ISSUE TITLE
Scratchr2 does not apply to the remix tree

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#21]
I don't know if this is just chrome or not:
![Screenshot 2020-08-27 at 7 05 57 AM](https://user-images.githubusercontent.com/61319150/91440158-c6880300-e833-11ea-85c0-ae0307574c70.png)

**Comment by Explosion-Scratch** [comment]
Dark mode is also still trying, but not really succeeding to make the page dark.

**Comment by mxmou** [comment]
I did notice the bug before but I didn't really work on this userstyle recently. I think it will be easy to fix, as the remix tree has worked correctly in the past.

**Comment by mxmou** [comment]
Probably won't be worked on. Use the Scratch Addons version of the userstyle instead.
