### ISSUE TITLE
Consider adding control of more colors?

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#22]
It seems that sometimes the secondary color is not controlled by stylus (chrome but maybe all browsers):
![Screenshot 2020-08-27 at 7 07 28 AM](https://user-images.githubusercontent.com/61319150/91440368-1cf54180-e834-11ea-9995-fa0c890b6e43.png)

**Comment by Explosion-Scratch** [comment]
![Screenshot 2020-08-27 at 7 09 40 AM](https://user-images.githubusercontent.com/61319150/91440961-0996a600-e835-11ea-9562-caf656ce2c29.png)

**Comment by mxmou** [comment]
Actually this is the primary color 😉

Since v1.2.0 (I think) the primary color and link color settings don't affect 3.0-styled pages, except a few elements such as the navigation bar. I decided not to fix this until I do some refactoring, which will hopefully happen soon.

**Comment by mxmou** [comment]
I plan to do this in Scratch Addons (ScratchAddons/ScratchAddons#645) but not here.
