### ISSUE TITLE
Some text on dark surfaces in dark mode is still dark

### ISSUE THREAD

**Issue by mxmou** [mxmou/customize-scratch#23]
This includes:

- the project share date: ![Project share date](https://user-images.githubusercontent.com/51849865/91445041-dd4f4980-e875-11ea-8491-266ef119841d.png)
- some icons on the project page: ![Project love, favorite etc. icons](https://user-images.githubusercontent.com/51849865/91445239-28695c80-e876-11ea-8213-1a552ec0398e.png)
- title of the ask box:
![Ask and wait input box with title](https://user-images.githubusercontent.com/51849865/91445903-06bca500-e877-11ea-8174-790b58423124.png)
(the input border should probably be brighter too - **edit:** it shouldn't, it's intentionally `#444` for consistency with rest of the UI)
- disabled items in the `scratch-blocks` context menu (won't be changed for the same reason as the border above):
![Context menu in the block editor, some items are disabled](https://user-images.githubusercontent.com/51849865/91446251-8480b080-e877-11ea-8276-b522a111384b.png)

Some of them should be white, some should be light gray. If you find another example of dark text on dark background please comment here instead of making a new issue.

These will probably be fixed in the refactoring update.

**Comment by Explosion-Scratch** [comment]
It seems that the [code] tags in the forums still have dark text in them with dark mode.

**Comment by mxmou** [comment]
> It seems that the [code] tags in the forums still have dark text in them with dark mode.

This is the current intended behavior: to make sure syntax highlighting doesn't break, they have dark text on light background. I might change this in the future though.

**Comment by Explosion-Scratch** [comment]
Could you make custom syntax colors?

**Comment by mxmou** [comment]
> Could you make custom syntax colors?

Yes, I will probably do that in the future.

**Comment by mxmou** [comment]
Another problem: block inputs when focused.

![Block input when focused](https://user-images.githubusercontent.com/51849865/93025343-7f548d00-f5fd-11ea-951f-e70c66b10432.png)

**Comment by mxmou** [comment]
Probably won't be worked on. Use the Scratch Addons version of the userstyle instead.
