### ISSUE TITLE
Scratchr2 userstyle refactoring

### ISSUE THREAD

**Issue by mxmou** [mxmou/customize-scratch#24]
I want to reorganize the code for the Scratchr2 userstyle a bit.

### Changes

The userstyle will be renamed to *Scratch 2.0 → 3.0*, which makes much more sense than the current name (`scratchr2` is the Scratch 2.0 website, but non-technical users probably don't know that). See #17

I'm also going to change the layout of the code. Currently there is
- code which applies to the whole Scratch website, mainly for customization of 3.0-styled pages; and
- code which only applies to the 2.0-styled pages.

I want to make all styles, except those who are only intended for specific pages, apply to all pages, and when something has to be styled differently on 2.0 and 3.0 pages I'm going to do something like this:
```stylus
#app .something
    color: red
#pagewrapper .something
    color: blue
```

I often used this pattern in the code before:
```stylus
.something
    if not dark
        color: black
    else
        color: white
```

I don't like that for two reasons: because it's unnecessarily four lines long and because `if not` tests sound strange. I think this is better:
```stylus
.something
    color: black
    if dark
        color: white
```

I will probably also move code around a bit, mainly because contributors tend to add new code to the end, while it would actually make more sense for it to be somewhere in the middle.

### Fixing bugs

I think this is a good opportunity for fixing #21, #22 and #23 (the issues are new but I was aware of these bugs for quite a long time).

Also #25, which is important if this becomes an addon too.

### Features

Although the purpose of this update is making the code easier to maintain and fix bugs, I'm also interesting in working on compatibility with other userstyles and userscripts, for example:
- [Material Scratch Forum Editor Buttons](https://github.com/easrng/material-scratch-forum-editor-buttons) by @easrng is not currently compatible with this userstyle's dark mode feature.
- Any others?

It would be best to work together with the developers of other userstyles and make some changes there too. This is especially important if this gets added to [Scratch Addons](https://github.com/ScratchAddons/ScratchAddons) at some point.

### Conclusion

I'm almost ready to start working on this, but I would like to see other people's opinions and suggestion (@Explosion-Scratch @tb148 @easrng @BoomerScratch @JeffaloBob @WorldLanguages) before. If you know any bugs, even if they aren't very noticeable, please make an issue.

**Comment by easrng** [comment]
Mabye set --dark to 1 on :root when dark mode is on, and set it to 0
otherwise. Then I can use invert(var(--dark, 0)) to support it on my
userstyle without adding a preprocessor.

**Comment by WorldLanguages** [comment]
Well, on Scratch Addons: technically userstyles are already supported (the Developer Tools addon uses them), however right now they're simple CSS files that are always injected.
Really, the conclusion I have right now is that there's no perfect way to port a userstyle with Stylus syntax... having the addon loader handle those is a bit too extreme, and having to split CSS files and load them through a userscript is ugly. However, the latter is what makes most sense to me.
So really, all I can suggest is to make your files easily split-able into simple CSS files?
If you want to customize custom colors, the userscript could use `addon.settings` to get the color, and then set it to a CSS variable, so that the CSS file can grab it.
For dark mode or not, the only option I can think of is conditional CSS loading (unless there's some hacky way of using CSS variables to only apply styles when a variable is 1 and not 0?)

**Comment by mxmou** [comment]
> Mabye set `--dark` to 1 on `:root` when dark mode is on, and set it to 0 otherwise. Then I can use `invert(var(--dark, 0))` to support it on my userstyle without adding a preprocessor.

Good idea, I'm going to use this.

@WorldLanguages It would be cool but you're probably right that having the addon loader handle Stylus syntax is too much.

You once mentioned dark mode could be a global setting so addons could provide separate CSS files for dark mode. To me this seems to be the best option. (Would then there be some built-in CSS for dark mode?)

For colors, I agree CSS variables should be used. Using a userscript to set them is an option but I think the addon loader could easily handle that too - maybe something like `var(--addon-<addon name>-<setting name>)`.

When thinking about this I think I will actually make a "refactoring update II" at some point which would split the code into several Stylus files and add a script that would automatically build the userstyle and the addon.

**Comment by WorldLanguages** [comment]
Sounds good.
Dark mode is yet TBD I guess... A global dark mode makes sense, I think, but the details I didn't think about yet.
If possible, make a version that uses CSS variables everywhere; then, using `dark_mode` or `if_setting_enabled` (both to be discussed and maybe implemented) you can set the values, without requiring any JavaScript.

**Comment by easrng** [comment]
The CSS variables option for dark mode only works for numeric values though.
For colors it gets verbose fast.

https://codepen.io/easrng/pen/OJNmQpd

**Comment by mxmou** [comment]
> The CSS variables option for dark mode only works for numeric values though. For colors it gets verbose fast. https://codepen.io/easrng/pen/OJNmQpd

It's probably best to use separate files for dark mode, or set the CSS variables using `addon.json`.

**Comment by WorldLanguages** [comment]
Oh, some feedback: I'm currently using an old version of the userstyle because I don't like the big comments new versions introduced. I know it's inconsistent because when I go to a project they look big again, but I mostly reply to profile comments only, so it's fine. Having that as an option would be nice.

**Comment by mxmou** [comment]
Part 1 of this (i.e. what is described in this issue) is almost done, just waiting for easrng/material-scratch-forum-editor-buttons#1 to be resolved. I will start working on the addon version (refactoring update II) soon.

> Oh, some feedback: I'm currently using an old version of the userstyle because I don't like the big comments new versions introduced. I know it's inconsistent because when I go to a project they look big again, but I mostly reply to profile comments only, so it's fine. Having that as an option would be nice.

I don't think having too many options is a good idea... Maybe the spacing between profile/studio comments could be decreased (to about 20px, current is 33px).

**Comment by WorldLanguages** [comment]
@mxmou I simply dislike the Scratch's bubble design tbh :P

**Comment by mxmou** [comment]
> @mxmou I simply dislike the Scratch's bubble design tbh :P

I don't think it's worth adding a new setting just because some people dislike something. If I did this it would make sense for almost every other feature to be optional, resulting in an absolutely overwhelming settings interface.

If you think smaller spacing would still be better than the current one, I'm going to change it.

**Comment by Explosion-Scratch** [comment]
I think the comment size is fine.

**Comment by mxmou** [comment]
@WorldLanguages What do your reactions (👍 🤔) mean?

**Comment by WorldLanguages** [comment]
lol it means you have a point but i'll still be using the old version of your userstyle that has no comment bubbles :P

**Comment by jeffalo** [comment]
> @mxmou I simply dislike the Scratch's bubble design tbh :P

yes but i think everyone likes consistency

**Comment by mxmou** [comment]
I implemented this when porting this userstyle to Scratch Addons, but I decided not to update this userstyle every time the addon version is changed so I don't plan to release the refactored version. I'm probably going to add a banner telling users to switch to Scratch Addons (although most people did that already).
