### ISSUE TITLE
Issues with ScratchAddons (See deleted comments addon)

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#25]
This is without dark mode:
![image](https://user-images.githubusercontent.com/61319150/91983420-40ffc980-ecf1-11ea-9051-1c6a68457519.png)
And this is with it:
![image](https://user-images.githubusercontent.com/61319150/91983470-5a087a80-ecf1-11ea-9f5c-5db024c4d4fe.png)
 I'm not sure if this is something you can fix or if it should be fixed over in ScratchAddons by @JeffaloBob.

**Comment by mxmou** [comment]
I think this is easiest to fix here.

**Comment by mxmou** [comment]
See ScratchAddons/ScratchAddons#291
