### ISSUE TITLE
Notices are the old style

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#27]
All of the notices are in the old style:
![Screenshot 2020-09-10 at 11 26 17 AM](https://user-images.githubusercontent.com/61319150/92809870-a18ea680-f382-11ea-898f-f0da09c77e66.png)

**Comment by mxmou** [comment]
For reference, 3.0 style notices look like this:

![Project could not save](https://user-images.githubusercontent.com/51849865/93016646-1819e700-f5c3-11ea-8c75-593e22f4e7e5.png)

They will get a close button in the future.

**Comment by mxmou** [comment]
The notices don't even work correctly for me (are empty), even without extensions, which might be a Scratch bug, but it means it doesn't make sense to fix this.
