### ISSUE TITLE
Studio comment issues

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#28]
The pfp is above the comment box instead of beside:
![image](https://user-images.githubusercontent.com/61319150/94579375-5d364e00-023e-11eb-96ac-ba2c19161ace.png)

**Comment by mxmou** [comment]
Can't reproduce (tested on Edge 85 and Firefox 78). Is it affected by the zoom level?

**Comment by Explosion-Scratch** [comment]
Yes. At 75% it works but nothing else.

**Comment by Explosion-Scratch** [comment]
Chrome (ChromeOS) latest version

**Comment by mxmou** [comment]
> Yes. At 75% it works but nothing else.

If so, making the box about 1 pixel smaller should fix the problem

**Comment by mxmou** [comment]
I think this is already fixed, at least in the Scratch Addons version.
