### ISSUE TITLE
Old loading icon

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#29]
Maybe replace this loader with a nice new css one?
![image](https://user-images.githubusercontent.com/61319150/94579447-74753b80-023e-11eb-8ac9-c52f7c6a7b3e.png)

**Comment by mxmou** [comment]
Scratch 3.0 doesn't have a comments loading animation. Should I use the "Saving project" icon (modified to be blue instead of white)?

**Comment by Explosion-Scratch** [comment]
Sure! Also feel free to use something from here: https://www.csswand.dev/ It has some cool ones.

**Comment by mxmou** [comment]
Won't fix for now, I think the old icon looks fine.
