### ISSUE TITLE
Box shadow on the studio description when in focus does not replace the outline.

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#30]
Maybe remove the dashed outline and add a little more padding to that box-shadow?
![image](https://user-images.githubusercontent.com/61319150/94579648-ae464200-023e-11eb-97f4-6e3d3a4e1de3.png)

**Comment by mxmou** [comment]
This (and the About me & WIWO boxes) should definitely be improved.

**Comment by Explosion-Scratch** [comment]
Okay! Thanks!

**Comment by mxmou** [comment]
Studio styles will be removed when the new scratch-www studio page is released.
