### ISSUE TITLE
Follow studio button is non-existant

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#31]
(Sorry for so many issues today)
But yeah, the follow studio button is just not there:
![image](https://user-images.githubusercontent.com/61319150/94579882-e2b9fe00-023e-11eb-9c3e-fd20343ca8ab.png)

**Comment by mxmou** [comment]
Can't reproduce. If you're using an ad blocker, try whitelisting Scratch.

**Comment by Explosion-Scratch** [comment]
Oh wait. Sorry lol. I whitelisted scratch and it works fine.
