### ISSUE TITLE
One can scroll past the delete or report dialogue

### ISSUE THREAD

**Issue by Explosion-Scratch** [mxmou/customize-scratch#32]
You can just scroll past the dialogue:
![image](https://user-images.githubusercontent.com/61319150/94580022-0b41f800-023f-11eb-8d22-721869129072.png)
Also, maybe reduce the border radius on that a little? 10px should be fine.

**Comment by mxmou** [comment]
Closing - theoretically this isn't a valid issue because this is a bug with Scratch itself, but I might try to fix it anyway.

The border radius should be the same as in 3.0 dialog boxes (report comment, add to studio).
